### ISSUE TITLE
Assistance Needed With Anonymous Message Board FreeCodeCamp Project

### ISSUE THREAD

**Issue by DarkGamer2** [victoria-lo/victoria-lo#1]
Umm Hi Victoria, not sure if I'm posting this in the right spot, hopefully I am. I'm having some difficulties with the anonymous message board project from freecodecamp and was wondering if I could get in contact with you for some assistance. I have provided a link to my replit code as well as screenshots of my progress so far. 

Link to my replit: https://replit.com/@DarkGamer25/FCC-Message-Board

Screenshots of my progress: ![image](https://user-images.githubusercontent.com/81314360/152903434-1827354c-b5fb-4ba1-a9b7-a51539d92633.png)![image](https://user-images.githubusercontent.com/81314360/152903444-68bcda1b-aed7-4eed-b37a-b395908d3ed1.png)![image](https://user-images.githubusercontent.com/81314360/152903464-a521f2da-2a76-47f6-bc57-348415de0daf.png)

**Comment by victoria-lo** [comment]
Hi @DarkGamer2 , sorry for replying late. I believe FCC has a [forum](https://forum.freecodecamp.org/) where you can ask and discuss the problems with the community there :)  Cheers!
